spring:
  application:
    name: scraping-investments
  kafka:
    bootstrap-servers: kafka:9092
    topic: 
      producer: scraping-topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
